### ISSUE TITLE
How to change default main layout to "boxed"?

### ISSUE THREAD

**Issue by nurzaman7** [iarouse/dist-material-design-admin#1]
I am trying to find the code related to the layout of the website.  Customizer.html file constains ng-model="main.layout" . I did not find it in app.js to make dafault layout to boxed. Please help me out.

**Comment by iarouse** [comment]
This repo is production code only.

If you want to get access to the full version (including source code, documentation and support), you can buy it at http://themeforest.net/user/arousing?ref=arousing
